mytodo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
]

todo/urls.py
from django.urls import path
from .views import TaskList, UpdateTask, CreateTask, DeleteTask


app_name = 'todo'
urlpatterns = [
    path('', TaskList.as_view(), name='index'),
    path('create', CreateTask.as_view(), name='create'),
    path('<int:pk>', UpdateTask.as_view(), name='update'),
    path('delete/<int:pk>', DeleteTask.as_view(), name='delete'),
]

todo/models.py
from django.db import models


class Task(models.Model):
	title = models.CharField(max_length=200)

	class Meta:
		ordering = ['-id']

todo/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import (
	CreateView,
	UpdateView,
	DeleteView
	)
from .models import Task
from django.urls import reverse


class TaskList(ListView):
	model = Task
	context_object_name = 'tasklist'
	template_name = 'todo/index.html'


class CreateTask(CreateView):
	model = Task
	fields = ['title']
	template_name = 'todo/create_task.html'

	def get_success_url(self):
		return reverse('todo:index')


class UpdateTask(UpdateView):
	model = Task
	fields = ['title']
	template_name = 'todo/update_task.html'

	def get_success_url(self):
		return reverse('todo:index')


class DeleteTask(DeleteView):
	model = Task
	template_name = 'todo/delete_task.html'

	def get_success_url(self):
		return reverse('todo:index')

templates/todo/base.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<title>mytodoapp</title>
</head>
<body class="mx-5 my-1">
{% block content %}

{% endblock %}
</body>
</html>

templates/todo/create_task.html
{% extends 'todo/base.html' %}


{% block content %}
<div class=" container bg-secondary px-5 py-5">
	<form method="post">
	
	<div class="form-group">
		{% csrf_token %}
	{{ form.as_p }}

	</div>
	<input class="btn-success" type="submit" name="" value="Save">
</form>

</div>
{% endblock %}

templates/todo/delete_task.html
{% extends 'todo/base.html' %}


{% block content %}
<div class=" container bg-secondary px-5 py-5">

<form method="post">
	{% csrf_token %}
    <h5>Have you completed  "{{ task.title }}"?</h5>
    <input class="btn-danger" type="submit" value="Delete">
</form>	
</div>
{% endblock %}

templates/todo/index.html
{% extends 'todo/base.html' %}


{% block content %}
<div class="container bg-secondary text-center px-5 py-3 ">
	<h2>YOUR TASKLIST</h2>
<a class='btn-success text-decoration-none px-1 py-1' href="{% url 'todo:create' %}">Add New Task</a>
{% for task in tasklist %}
<div class="container mx-4 my-3 px-3 py-3 pr-5" style="background: #a7a8a8">

<h5 style="display: inline" class="">{{ task.title }}</h5>
<a href="{% url 'todo:delete' task.id %}" class="float-right text-danger "><i class="fa fa-trash fa-lg" aria-hidden="true"></i></a>

<a href="{% url 'todo:update' task.id %}" class="float-right mr-3" ><i class="fa fa-edit fa-lg"></i></a>

</div>
<div></div>
{% endfor %}
</div>
{% endblock %}

templates/todo/update_task.html
{% extends 'todo/base.html' %}


{% block content %}
<div class=" container bg-secondary px-5 py-5">
	<form method="post">
	
	<div class="form-group">
		{% csrf_token %}
	{{ form.as_p }}

	</div>
	<input class="btn-success" type="submit" name="" value="update">
</form>

</div>
{% endblock %}